option('battstat', type: 'feature', value: 'auto', description: 'Build battery status applet')
option('cpufreq', type: 'feature', value: 'auto', description: 'Build CPU frequency applet')
option('gtop-applets', type: 'feature', value: 'auto', description: 'Build libgtop applets')
option('invest', type: 'feature', value: 'auto', description: 'Build invest applet')
option('mateweather', type: 'feature', value: 'auto', description: 'Build weather applet')
option('timer', type: 'feature', value: 'auto', description: 'Build timer applet')
option('stickynotes', type: 'feature', value: 'auto', description: 'Build sticky notes applet')
option('accessx', type: 'feature', value: 'auto', description: 'Build X11 keyboard accessibility status applet')
option('polkit', type: 'feature', value: 'auto', description: 'Build PolicyKit support for cpufreq')
option('nl', type: 'feature', value: 'auto', description: 'Build libnl support for netspeed')
option('iw', type: 'feature', value: 'disabled', description: 'Build iwlib support for netspeed')
